# Generated by Django 6.1.1 on 2026-09-13 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ShakeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_required', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('shake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.shake')),
            ],
            options={
                'unique_together': {('shake', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='shake',
            name='ingredients',
            field=models.ManyToManyField(through='inventory.ShakeIngredient', to='inventory.ingredient'),
        ),
    ]
