# Generated by Django 6.1.1 on 2026-09-13 02:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_shake_shakeingredient_shake_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('shake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.shake')),
            ],
        ),
    ]
