# Generated by Django 6.1.1 on 2026-09-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_store_restock'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6),
        ),
    ]
